<h3> Q1

In [12]:
## (1) 행렬 A의 최소제곱해 구하기 
## 편의상 파이썬 이용해서 구하겠습니다.

import numpy as np

## Ax = b의 형태 만들기
A = np.array([[1, 3, 5], [1, 1, 0], [1, 1, 2], [1, 3, 3]])
b = np.array([2, 3, -1, 2])

## 정규방정식은 AT * Ax = AT * b이므로 양변에 a의 전치행렬 곱하기
AtA = np.dot(A.T, A)
Atb = np.dot(A.T, b)

print('좌변(AtA)의 형태\n', AtA)
print('우변(Atb)의 형태\n', Atb)

## 즉, 4x1 + 8x2 + 10x3 = 6, 8x1 + 20x2 + 26x3 = 14, 10x1 + 26x2 + 38x3 = 14를 풀어야함.
## 방정식 해 구하기 -> numpy에서는 방정식의 해를 구할 수 있도록 하는 메서드 존재

x = np.linalg.solve(AtA, Atb)
print('최소제곱해 : ', x) ## (0, 2, -1)


##======================================================##
# (2) |b-Ax| 구하기 
Ax = np.dot(A, x)
print('최소제곱해에서 오차로 이루어진 행렬 : ', b - Ax)

error = np.linalg.norm(b-Ax)
print('최소제곱해에서의 오차 : ', error) ## 최종 오차 2

좌변(AtA)의 형태
 [[ 4  8 10]
 [ 8 20 26]
 [10 26 38]]
우변(Atb)의 형태
 [ 6 14 14]
최소제곱해 :  [ 4.4408921e-17  2.0000000e+00 -1.0000000e+00]
최소제곱해에서 오차로 이루어진 행렬 :  [ 1.  1. -1. -1.]
최소제곱해에서의 오차 :  1.9999999999999998


<h3> Q2 </h3>

In [13]:
import numpy as np

## 모든 값이 0인 100 x 2 행렬 X 만들기 
X = np.zeros((100, 2))

## 첫 번째 열과 두 번째 열에 각각 요구한 대로 값 집어넣기
X[:, 0] = np.random.randint(10, 100, 100)
X[:, 1] = np.random.randint(100, 2000, 100)

print('첫 번째 열과 두 번째 열에 들어간 결과\n')
print(X[:, 0])
print()
print(X[:, 1])
print()

## X와 동일한 크기를 갖는 행렬 만들기 (standard_x)
standard_x = np.zeros_like(X)
print('standard_x : ', standard_x.shape)

## X를 표준정규분포로 표준화 하기
standard_x[:, 0] = (X[:, 0] - X[:, 0].mean()) / X[:, 0].std()
standard_x[:, 1] = (X[:, 1] - X[:, 1].mean()) / X[:, 1].std()

column_0_mean, column_0_std = standard_x[:, 0].mean(), standard_x[:, 0].std()
column_1_mean, column_1_std = standard_x[:, 1].mean(), standard_x[:, 1].std()

print('표준화된 X : ', standard_x)
print('표준화 결과 확인하기 -> {}, {}, {}, {}'.format(column_0_mean, column_1_mean, column_0_std, column_1_std))

첫 번째 열과 두 번째 열에 들어간 결과

[71. 42. 56. 40. 85. 59. 51. 49. 48. 64. 87. 40. 33. 20. 51. 13. 66. 88.
 11. 73. 56. 89. 98. 73. 39. 76. 96. 92. 14. 52. 25. 77. 16. 96. 44. 58.
 35. 68. 48. 58. 19. 49. 33. 27. 28. 77. 28. 15. 34. 53. 14. 10. 30. 69.
 23. 43. 38. 39. 76. 89. 82. 74. 52. 74. 56. 66. 66. 98. 60. 62. 82. 28.
 84. 74. 36. 21. 18. 57. 42. 42. 91. 96. 86. 45. 84. 58. 86. 49. 39. 19.
 41. 48. 35. 21. 84. 38. 80. 70. 50. 53.]

[ 974. 1333.  710. 1954. 1366. 1182. 1013. 1163. 1062.  845. 1429.  687.
  289. 1065. 1794.  447. 1611.  267. 1263. 1220.  290.  728.  646. 1153.
  470.  621.  312.  976.  799.  601. 1332. 1537. 1696. 1691. 1421. 1703.
 1683.  270. 1603. 1970.  784.  563.  222.  983. 1650. 1928. 1937. 1184.
  823.  822. 1320.  456. 1070. 1579. 1853.  896.  130.  777.  674. 1578.
 1674. 1797. 1052.  448.  449. 1136.  201. 1363.  549.  346.  835.  919.
  312. 1749. 1725.  967. 1410.  901.  470. 1783.  787. 1753. 1184. 1711.
 1436.  867.  646.  126. 1970.  700.  365. 1311.  354. 14

<h3> Q3 </h3>

In [15]:
data_arr = np.loadtxt('population.csv', delimiter = ',', dtype = np.int64)
print("[Data Loaded]:", data_arr.shape, '\n')

[Data Loaded]: (463447, 3) 



<h4> (1) 연령대별 남녀 성비 출력 </h4>

In [18]:
## 기준이 20대, 30대, 40대, 50대이므로 lookup table 생성
### 코드 동작 방식 -> 첫 번째는 20대 미만이니까 0 ~ 20, 마지막은 50대 이상이니까 50 ~ 150
lookup_table = np.array([0, 20, 30, 40, 50, 150])
title = ["20대미만\t", "20대\t", "30대\t", "40대\t", "50대이상\t"]

print('\t\t남성\t여성')
for i, lookup_age in enumerate(title):

    # row_ages : 조건에 맞는 연령대를 슬라이싱 기법 및 불린 인덱싱 이용하여 추출
    # boys_ratio : 연령대별로 추출 후에 남성 비율 측정
    # 남성 비율 측정 후 여성 비율은 1 - boys_ratio의 형태로 계산
    row_ages = data_arr[(data_arr[:, 1] >= lookup_table[i]) & (data_arr[:, 1] < lookup_table[i+1])]
    boys_ratio = len(row_ages[row_ages[:, 0] == 1]) / len(row_ages)
    print(title[i] +'\t{:.2f}\t{:.2f}'.format(boys_ratio, 1 - boys_ratio))

		남성	여성
20대미만		0.51	0.49
20대		0.50	0.50
30대		0.51	0.49
40대		0.50	0.50
50대이상		0.46	0.54


<h4> (2) 연령대별/성별, 전체 대학 진학률 출력

In [30]:
## 기준이 20대, 30대, 40대, 50대이므로 lookup table 생성
### 코드 동작 방식 -> 첫 번째는 20대 미만이니까 0 ~ 20, 마지막은 50대 이상이니까 50 ~ 150
lookup_table = np.array([20, 30, 40, 50, 150])
title = ["20대\t", "30대\t", "40대\t", "50대이상\t"]

print('\t\t남성\t여성\t전체')
for i, lookup_age in enumerate(title):

    # row_ages : 조건에 맞는 연령대를 슬라이싱 기법 및 불린 인덱싱 이용하여 추출
    # row_ages_univ : 해당 연령대에서 대학에 입학한 사람만 추출
    # univ_ratio : 해당 연령대에서 대학에 입학하는 사람들의 비율 
    # boys_univ_ratio : 해당 연령대에서 대학에 입학하는 사람들 중에서 남자의 비율 => 1 - boys_univ_ratio : 여자의 비율
    row_ages = data_arr[(data_arr[:, 1] >= lookup_table[i]) & (data_arr[:, 1] < lookup_table[i+1])]
    row_ages_univ = row_ages[row_ages[:, 2] >= 5]
    univ_ratio = len(row_ages_univ) / len(row_ages)
    boys_univ_ratio = len(row_ages_univ[row_ages_univ[:, 0] == 1]) / len(row_ages_univ)
    print(title[i] + '\t{:.2f}\t{:.2f}\t{:.2f}'.format(boys_univ_ratio, 1 - boys_univ_ratio\
        ,univ_ratio))
    

		남성	여성	전체
20대		0.48	0.52	0.81
30대		0.51	0.49	0.80
40대		0.52	0.48	0.61
50대이상		0.62	0.38	0.23


In [37]:
## 기준이 20대, 30대, 40대, 50대이므로 lookup table 생성
### 코드 동작 방식 -> 첫 번째는 20대 미만이니까 0 ~ 20, 마지막은 50대 이상이니까 50 ~ 150
lookup_table = np.array([20, 30, 40, 50, 150])
title = ["20대\t", "30대\t", "40대\t", "50대이상\t"]

print('\t\t남성\t여성\t전체')
for i, lookup_age in enumerate(title):

    # row_ages : 조건에 맞는 연령대를 슬라이싱 기법 및 불린 인덱싱 이용하여 추출
    # row_ages_univ : 해당 연령대에서 대학에 입학한 사람만 추출
    # univ_ratio : 해당 연령대에서 대학에 입학하는 사람들의 비율 
    # boys_univ_ratio : 해당 연령대, 남자 중에서 대학에 입학하는 사람들의 비율
    # girls_univ_ratio : 해당 연령대, 여자 중에서 대학에 입학하는 사람들의 비율
    row_ages = data_arr[(data_arr[:, 1] >= lookup_table[i]) & (data_arr[:, 1] < lookup_table[i+1])]
    row_ages_univ = row_ages[row_ages[:, 2] >= 5]
    univ_ratio = len(row_ages_univ) / len(row_ages)
    boys_univ_ratio = len(row_ages_univ[row_ages_univ[:, 0] == 1]) / len(row_ages[row_ages[:, 0] == 1])
    girls_univ_ratio = len(row_ages_univ[row_ages_univ[:, 0] == 1]) / len(row_ages[row_ages[:, 0] == 2])
    print(title[i] + '\t{:.2f}\t{:.2f}\t{:.2f}'.format(boys_univ_ratio, girls_univ_ratio\
        ,univ_ratio))
    

		남성	여성	전체
20대		0.78	0.78	0.81
30대		0.80	0.84	0.80
40대		0.63	0.63	0.61
50대이상		0.31	0.27	0.23
