<h3> 1. 라이브러리 불러오기 </h3>
<h5> (1) 행렬 만들기 </h5>

In [6]:
import numpy as np

# 벡터 만들기 np.array
vector_x = np.array([1, 2, 3])

# 행렬 만들기 np.array
matrix_x = np.array([[1, 2, 3], [2, 3, 1]])
print(matrix_x)

# 행렬 x의 크기 확인하기 x.shape
print('행렬 x의 크기는 : {}'.format(matrix_x.shape)) # 행렬 X의 크기는 2 x 3

# 행렬 x의 type 확인하기 x.dtype
print('행렬 x의 타입은 : {}'.format(matrix_x.dtype)) # 행렬 X는 정수의 요소를 가지는 형태

matrix_float_x = np.array([[1, 2, 3], [2, 3, 1]], dtype = 'float64') # 행렬 x의 요소를 float으로 하는 경우
print(matrix_float_x)

[[1 2 3]
 [2 3 1]]
행렬 x의 크기는 : (2, 3)
행렬 x의 타입은 : int32
[[1. 2. 3.]
 [2. 3. 1.]]


<h5> (2) 행렬의 초기화 </h5>

In [17]:
matrix_zero_x = np.zeros((3, 2)) # 3 x 2 행렬의 요소를 모두 0으로 초기화
print('matrix_zero_x의 행렬\n', matrix_zero_x)
print()
matrix_empty_x = np.empty((3, 2)) # 3 x 2 행렬을 임의의 값으로 초기화
print('matrix_empty_x의 행렬\n', matrix_empty_x)
print()
matrix_ones_x = np.ones((3, 3)) # 3 x 3 행렬의 모든 요소를 1로 초기화
print('matrix_ones_x의 행렬\n', matrix_ones_x)
print()

# np.arange(a, b, c) : a부터 b-1까지 c의 간격으로 생성
# np.arange(a) : 0부터 a-1까지 1의 간격으로 생성
matrix_A = np.arange(1, 5, 1)
print('matrix_A의 행렬\n', matrix_A)
print()

matrix_B = np.arange(1, 10)
print('matrix_B의 행렬\n', matrix_B)
print()

# np.linspace(from, to, npoints) : from부터 to까지 일정 간격으로 npoints개 생성
matrix_C = np.linspace(0., 20., 11)
print('matrix_C의 행렬\n', matrix_C)

matrix_zero_x의 행렬
 [[0. 0.]
 [0. 0.]
 [0. 0.]]

matrix_empty_x의 행렬
 [[0. 0.]
 [0. 0.]
 [0. 0.]]

matrix_ones_x의 행렬
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

matrix_A의 행렬
 [1 2 3 4]

matrix_B의 행렬
 [1 2 3 4 5 6 7 8 9]

matrix_C의 행렬
 [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


<h5> (3) 차원 변경하기 </h5>

In [22]:
X = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print('X의 행렬\n', X)
print()
# reshape를 이용하여 적절하게 차원 변경
X.shape = (3, 3)
print('X의 행렬\n', X)
print()

Y = np.arange(9.)
print('Y의 행렬\n', Y)
print()
Y = np.arange(9.).reshape((3, 3))
print('Y의 행렬\n', Y)

X의 행렬
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

X의 행렬
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Y의 행렬
 [0. 1. 2. 3. 4. 5. 6. 7. 8.]

Y의 행렬
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


<h3> 2. 행렬의 연산 </h3>

In [36]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[2., 3., 1.], [5., 4., 6.]])
arr3 = np.array([[1, 2], [3, 4], [5, 6]])

print('arr1의 행렬\n', arr1)
print()

print('arr1 + arr2의 결과\n', arr1 + arr2) # np.add(arr1, arr2)
print()
print('arr1 - arr2의 결과\n', arr1 - arr2) # np.sub(arr1, arr2)
print()
print('arr1 * arr2의 결과\n', arr1 * arr2) #np.multiply(arr1, arr2)
print()
print('arr1 * 2 + arr2 * 3의 결과\n', 2 * arr1 + 3 * arr2)

arr1_dot_arr3 = np.dot(arr1, arr3)
arr2_dot_arr3 = np.dot(arr2, arr3)
arr3_dot_arr2 = np.dot(arr3, arr2)

print('arr1과 arr2의 내적 결과\n', arr1_dot_arr3)
print()

print('arr2과 arr3의 내적 결과\n', arr2_dot_arr3)
print()

print('arr3과 arr2의 내적 결과\n', arr3_dot_arr2)
print()


arr1의 행렬
 [[1. 2. 3.]
 [4. 5. 6.]]

arr1 + arr2의 결과
 [[ 3.  5.  4.]
 [ 9.  9. 12.]]

arr1 - arr2의 결과
 [[-1. -1.  2.]
 [-1.  1.  0.]]

arr1 * arr2의 결과
 [[ 2.  6.  3.]
 [20. 20. 36.]]

arr1 * 2 + arr2 * 3의 결과
 [[ 8. 13.  9.]
 [23. 22. 30.]]
arr1과 arr2의 내적 결과
 [[22. 28.]
 [49. 64.]]

arr2과 arr3의 내적 결과
 [[16. 22.]
 [47. 62.]]

arr3과 arr2의 내적 결과
 [[12. 11. 13.]
 [26. 25. 27.]
 [40. 39. 41.]]



<h3> 3. 인덱싱과 슬라이싱 </h3>

<h5> (1) 기본 인덱싱 </h5>

In [64]:
arr = np.linspace(1, 19, 10)
arr2 = np.arange(16).reshape((4, 4))

print('벡터 arr의 결과\n', arr)
print()
print('arr[5:8]의 결과\n', arr[5:8])
print()
print('arr[[0, 2, 4]]의 결과\n', arr[[0, 2, 4]])
print()
print('arr2의 결과\n', arr2)
print()

print('arr2[[1, 2], [1, 2]]의 결과\n', arr2[[1, 2], [1, 2]])
print()
print('arr2[1:, 1:3]의 결과\n', arr2[1:, 1:3])
print()

# 슬라이싱 이용해서 값 대입 가능
arr2[:2, 1:] = 20
print(arr2)

# 따로 추출해서 이용 가능
tmp = arr2[:3, 1:3]
tmp[2:, :] = 15
print('tmp의 결과\n', tmp)
print()
print('arr2의 결과\n', arr2)

벡터 arr의 결과
 [ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]

arr[5:8]의 결과
 [11. 13. 15.]

arr[[0, 2, 4]]의 결과
 [1. 5. 9.]

arr2의 결과
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

arr2[[1, 2], [1, 2]]의 결과
 [ 5 10]

arr2[1:, 1:3]의 결과
 [[ 5  6]
 [ 9 10]
 [13 14]]

[[ 0 20 20 20]
 [ 4 20 20 20]
 [ 8  9 10 11]
 [12 13 14 15]]
tmp의 결과
 [[20 20]
 [20 20]
 [15 15]]

arr2의 결과
 [[ 0 20 20 20]
 [ 4 20 20 20]
 [ 8 15 15 11]
 [12 13 14 15]]


<h5> (2) 불린 인덱싱 </h5>

In [59]:
arr = np.linspace(1, 19, 10)
arr2 = np.arange(16).reshape((4, 4))

mask = arr > 10
arr > 10
print('arr > 10인 배열만 추출\n', arr[arr > 10])
print()

print('arr2', arr2)
print('arr2 > 10인 배열만 추출\n', arr2[arr2 > 10])

arr > 10인 배열만 추출
 [11. 13. 15. 17. 19.]

arr2 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
arr2 > 10인 배열만 추출
 [11 12 13 14 15]


<h3> (3) 배열 합치기 </h3>

In [71]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('a와 b를 세로로 합치기\n', np.vstack((a, b)))
print()
print('a와 b를 가로로 합치기\n', np.hstack((a, b)))
print()

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print('a와 b를 행으로 합치기\n', np.concatenate((a, b), axis = 0))
print()

a와 b를 세로로 합치기
 [[1 2 3]
 [4 5 6]]

a와 b를 가로로 합치기
 [1 2 3 4 5 6]

a와 b를 행으로 합치기
 [[1 2]
 [3 4]
 [5 6]]



<h3> 4. 여러 가지 행렬 </h3>

In [76]:
A = np.arange(9).reshape((3, 3))
print('A의 전치행렬\n', A.T) 
print()
print('A의 전치행렬\n', np.transpose(A))

# 정사각행렬
B = np.identity(7) # 7 x 7 정사각행렬, 주대각성분 1
print('B의 행렬\n', B)
print()

# A의 역행렬 구하기
C = np.array([[4, 2], [5, 3]])
print('C의 역행렬\n', np.linalg.inv(C))

A의 전치행렬
 [[0 3 6]
 [1 4 7]
 [2 5 8]]

A의 전치행렬
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
B의 행렬
 [[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]

C의 역행렬
 [[ 1.5 -1. ]
 [-2.5  2. ]]


<h3> 5. 그 밖의 함수 </h3>

<h5> (1) 랜덤 함수 </h5>

In [78]:
np.random.rand(3) #0부터 1 사이의 숫자 3개 반환

array([0.57469634, 0.26216606, 0.42513903])

In [79]:
np.random.rand(3, 5) #0부터 1 사이의 숫자를 3 x 5 행렬로 반환

array([[0.67231241, 0.41228781, 0.44366307, 0.99316166, 0.34278043],
       [0.95481877, 0.6143226 , 0.53676598, 0.76712036, 0.07843827],
       [0.76832386, 0.19988742, 0.34024407, 0.41966822, 0.77134269]])

In [80]:
np.random.randn(3) #표준정규분포를 따르는 집단에서 3개 추출

array([ 0.1877741 , -0.71267629,  0.52013338])

In [81]:
np.random.randn(3, 6) # 표준정규분포를 따르는 집단에서 3 x 6 행렬의 형태로 추출

array([[ 1.1556015 , -0.52078589,  1.62022275,  0.99604961,  2.02853272,
         1.03033255],
       [-0.05672287, -0.250568  , -0.9435041 ,  0.35162759,  2.03378277,
         0.19908701],
       [-2.09185286,  1.85390267,  0.03790243,  0.12386057, -0.88881633,
        -1.29411239]])

In [82]:
np.random.randint(100) # 0부터 100 사이의 정수를 아무거나 하나 추출

24

In [83]:
np.random.randint(100, size = 10) # 0부터 100 사이의 정수를 아무거나 10개 추출

array([43, 57, 62, 56, 66, 99, 90, 98, 98,  2])

In [84]:
np.random.randint(100, size = (2, 5)) # 0부터 100 사이의 정수를 아무거나 10개 추출하고 2 x 5 행렬로 표현

array([[17, 48, 87, 64,  4],
       [61, 35,  2, 68,  1]])

In [85]:
np.random.normal(100, 10, size = (2, 5)) # 평균이 100이고 표준편차가 10인 정규분포를 따르는 집단에서 10개 추출 후, 2 x 5 행렬로 표현

array([[108.15601453,  96.14158713,  96.75996789,  96.80961323,
         89.89123224],
       [ 93.45330442, 122.68591705, 102.80988641,  99.31806642,
         99.8498359 ]])

<h5> (2) 수학 표현 </h5>

In [92]:
import random

np.random.seed(42)
a = np.random.normal(0, 3, size = (4, 4))
print(a)

[[ 1.49014246 -0.4147929   1.94306561  4.56908957]
 [-0.70246012 -0.70241087  4.73763845  2.30230419]
 [-1.40842316  1.62768013 -1.39025308 -1.39718926]
 [ 0.72588681 -5.73984073 -5.1747535  -1.68686259]]


In [93]:
np.sin(a)

array([[ 0.99674924, -0.4030004 ,  0.93150434, -0.9897502 ],
       [-0.64609734, -0.64605975, -0.99968125,  0.74416801],
       [-0.98684641,  0.99838255, -0.98374629, -0.9849681 ],
       [ 0.66379896,  0.51700178,  0.89500027, -0.99327187]])

In [94]:
np.cos(a)

array([[ 0.08056645,  0.9151998 , -0.36373022, -0.14280948],
       [ 0.76325502,  0.76328684,  0.02524678, -0.6679925 ],
       [ 0.16166061, -0.05685313,  0.17956402,  0.17273631],
       [ 0.74791105,  0.85598432,  0.4460656 , -0.11580584]])

In [95]:
np.exp(a)

array([[4.43772767e+00, 6.60477049e-01, 6.98011655e+00, 9.64562530e+01],
       [4.95365144e-01, 4.95389543e-01, 1.14164278e+02, 9.99719134e+00],
       [2.44528562e-01, 5.09204812e+00, 2.49012277e-01, 2.47291059e-01],
       [2.06656295e+00, 3.21528032e-03, 5.65761136e-03, 1.85099347e-01]])

In [96]:
np.sqrt(a)

C:\Users\revol\AppData\Local\Temp/ipykernel_35384/2835837605.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(a)


array([[1.22071391,        nan, 1.39393888, 2.13754288],
       [       nan,        nan, 2.17661169, 1.51733457],
       [       nan, 1.27580568,        nan,        nan],
       [0.85198991,        nan,        nan,        nan]])